# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := sync_proto_cpp
### Rules for final target.
$(obj).target/chrome/browser/sync/protocol/sync_proto_cpp.stamp: TOOLSET := $(TOOLSET)
$(obj).target/chrome/browser/sync/protocol/sync_proto_cpp.stamp: $(obj).target/third_party/protobuf2/libprotobuf.a $(obj).target/chrome/browser/sync/protocol/sync_proto.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/chrome/browser/sync/protocol/sync_proto_cpp.stamp
# Add target alias
.PHONY: sync_proto_cpp
sync_proto_cpp: $(obj).target/chrome/browser/sync/protocol/sync_proto_cpp.stamp

# Add target alias to "all" target.
.PHONY: all
all: sync_proto_cpp

