# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := sync_proto
### Generated for rule sync_proto_genproto:
$(builddir)/pyproto/sync_pb/sync_pb2.py: obj := $(abs_obj)

$(builddir)/pyproto/sync_pb/sync_pb2.py: builddir := $(abs_builddir)

$(builddir)/pyproto/sync_pb/sync_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync_pb/sync_pb2.py: chrome/browser/sync/protocol/sync.proto $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,sync_proto_genproto_0)
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/sync.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/sync.pb.cc: $(builddir)/pyproto/sync_pb/sync_pb2.py
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/sync.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/sync.pb.cc: ;

all_deps += $(builddir)/pyproto/sync_pb/sync_pb2.py $(obj)/gen/protoc_out/chrome/browser/sync/protocol/sync.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/sync.pb.cc
cmd_sync_proto_genproto_0 = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd chrome/browser/sync/protocol; mkdir -p $(obj)/gen/protoc_out/chrome/browser/sync/protocol $(builddir)/pyproto/sync_pb; "$(builddir)/protoc" "--proto_path=." "./sync$(suffix $<)" "--cpp_out=$(obj)/gen/protoc_out/chrome/browser/sync/protocol" "--python_out=$(builddir)/pyproto/sync_pb"
quiet_cmd_sync_proto_genproto_0 = RULE sync_proto_genproto_0 $@

$(builddir)/pyproto/sync_pb/encryption_pb2.py: obj := $(abs_obj)

$(builddir)/pyproto/sync_pb/encryption_pb2.py: builddir := $(abs_builddir)

$(builddir)/pyproto/sync_pb/encryption_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync_pb/encryption_pb2.py: chrome/browser/sync/protocol/encryption.proto $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,sync_proto_genproto_1)
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/encryption.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/encryption.pb.cc: $(builddir)/pyproto/sync_pb/encryption_pb2.py
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/encryption.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/encryption.pb.cc: ;

all_deps += $(builddir)/pyproto/sync_pb/encryption_pb2.py $(obj)/gen/protoc_out/chrome/browser/sync/protocol/encryption.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/encryption.pb.cc
cmd_sync_proto_genproto_1 = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd chrome/browser/sync/protocol; mkdir -p $(obj)/gen/protoc_out/chrome/browser/sync/protocol $(builddir)/pyproto/sync_pb; "$(builddir)/protoc" "--proto_path=." "./encryption$(suffix $<)" "--cpp_out=$(obj)/gen/protoc_out/chrome/browser/sync/protocol" "--python_out=$(builddir)/pyproto/sync_pb"
quiet_cmd_sync_proto_genproto_1 = RULE sync_proto_genproto_1 $@

$(builddir)/pyproto/sync_pb/autofill_specifics_pb2.py: obj := $(abs_obj)

$(builddir)/pyproto/sync_pb/autofill_specifics_pb2.py: builddir := $(abs_builddir)

$(builddir)/pyproto/sync_pb/autofill_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync_pb/autofill_specifics_pb2.py: chrome/browser/sync/protocol/autofill_specifics.proto $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,sync_proto_genproto_2)
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/autofill_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/autofill_specifics.pb.cc: $(builddir)/pyproto/sync_pb/autofill_specifics_pb2.py
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/autofill_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/autofill_specifics.pb.cc: ;

all_deps += $(builddir)/pyproto/sync_pb/autofill_specifics_pb2.py $(obj)/gen/protoc_out/chrome/browser/sync/protocol/autofill_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/autofill_specifics.pb.cc
cmd_sync_proto_genproto_2 = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd chrome/browser/sync/protocol; mkdir -p $(obj)/gen/protoc_out/chrome/browser/sync/protocol $(builddir)/pyproto/sync_pb; "$(builddir)/protoc" "--proto_path=." "./autofill_specifics$(suffix $<)" "--cpp_out=$(obj)/gen/protoc_out/chrome/browser/sync/protocol" "--python_out=$(builddir)/pyproto/sync_pb"
quiet_cmd_sync_proto_genproto_2 = RULE sync_proto_genproto_2 $@

$(builddir)/pyproto/sync_pb/bookmark_specifics_pb2.py: obj := $(abs_obj)

$(builddir)/pyproto/sync_pb/bookmark_specifics_pb2.py: builddir := $(abs_builddir)

$(builddir)/pyproto/sync_pb/bookmark_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync_pb/bookmark_specifics_pb2.py: chrome/browser/sync/protocol/bookmark_specifics.proto $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,sync_proto_genproto_3)
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/bookmark_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/bookmark_specifics.pb.cc: $(builddir)/pyproto/sync_pb/bookmark_specifics_pb2.py
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/bookmark_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/bookmark_specifics.pb.cc: ;

all_deps += $(builddir)/pyproto/sync_pb/bookmark_specifics_pb2.py $(obj)/gen/protoc_out/chrome/browser/sync/protocol/bookmark_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/bookmark_specifics.pb.cc
cmd_sync_proto_genproto_3 = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd chrome/browser/sync/protocol; mkdir -p $(obj)/gen/protoc_out/chrome/browser/sync/protocol $(builddir)/pyproto/sync_pb; "$(builddir)/protoc" "--proto_path=." "./bookmark_specifics$(suffix $<)" "--cpp_out=$(obj)/gen/protoc_out/chrome/browser/sync/protocol" "--python_out=$(builddir)/pyproto/sync_pb"
quiet_cmd_sync_proto_genproto_3 = RULE sync_proto_genproto_3 $@

$(builddir)/pyproto/sync_pb/extension_specifics_pb2.py: obj := $(abs_obj)

$(builddir)/pyproto/sync_pb/extension_specifics_pb2.py: builddir := $(abs_builddir)

$(builddir)/pyproto/sync_pb/extension_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync_pb/extension_specifics_pb2.py: chrome/browser/sync/protocol/extension_specifics.proto $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,sync_proto_genproto_4)
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/extension_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/extension_specifics.pb.cc: $(builddir)/pyproto/sync_pb/extension_specifics_pb2.py
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/extension_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/extension_specifics.pb.cc: ;

all_deps += $(builddir)/pyproto/sync_pb/extension_specifics_pb2.py $(obj)/gen/protoc_out/chrome/browser/sync/protocol/extension_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/extension_specifics.pb.cc
cmd_sync_proto_genproto_4 = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd chrome/browser/sync/protocol; mkdir -p $(obj)/gen/protoc_out/chrome/browser/sync/protocol $(builddir)/pyproto/sync_pb; "$(builddir)/protoc" "--proto_path=." "./extension_specifics$(suffix $<)" "--cpp_out=$(obj)/gen/protoc_out/chrome/browser/sync/protocol" "--python_out=$(builddir)/pyproto/sync_pb"
quiet_cmd_sync_proto_genproto_4 = RULE sync_proto_genproto_4 $@

$(builddir)/pyproto/sync_pb/nigori_specifics_pb2.py: obj := $(abs_obj)

$(builddir)/pyproto/sync_pb/nigori_specifics_pb2.py: builddir := $(abs_builddir)

$(builddir)/pyproto/sync_pb/nigori_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync_pb/nigori_specifics_pb2.py: chrome/browser/sync/protocol/nigori_specifics.proto $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,sync_proto_genproto_5)
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/nigori_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/nigori_specifics.pb.cc: $(builddir)/pyproto/sync_pb/nigori_specifics_pb2.py
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/nigori_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/nigori_specifics.pb.cc: ;

all_deps += $(builddir)/pyproto/sync_pb/nigori_specifics_pb2.py $(obj)/gen/protoc_out/chrome/browser/sync/protocol/nigori_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/nigori_specifics.pb.cc
cmd_sync_proto_genproto_5 = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd chrome/browser/sync/protocol; mkdir -p $(obj)/gen/protoc_out/chrome/browser/sync/protocol $(builddir)/pyproto/sync_pb; "$(builddir)/protoc" "--proto_path=." "./nigori_specifics$(suffix $<)" "--cpp_out=$(obj)/gen/protoc_out/chrome/browser/sync/protocol" "--python_out=$(builddir)/pyproto/sync_pb"
quiet_cmd_sync_proto_genproto_5 = RULE sync_proto_genproto_5 $@

$(builddir)/pyproto/sync_pb/password_specifics_pb2.py: obj := $(abs_obj)

$(builddir)/pyproto/sync_pb/password_specifics_pb2.py: builddir := $(abs_builddir)

$(builddir)/pyproto/sync_pb/password_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync_pb/password_specifics_pb2.py: chrome/browser/sync/protocol/password_specifics.proto $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,sync_proto_genproto_6)
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/password_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/password_specifics.pb.cc: $(builddir)/pyproto/sync_pb/password_specifics_pb2.py
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/password_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/password_specifics.pb.cc: ;

all_deps += $(builddir)/pyproto/sync_pb/password_specifics_pb2.py $(obj)/gen/protoc_out/chrome/browser/sync/protocol/password_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/password_specifics.pb.cc
cmd_sync_proto_genproto_6 = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd chrome/browser/sync/protocol; mkdir -p $(obj)/gen/protoc_out/chrome/browser/sync/protocol $(builddir)/pyproto/sync_pb; "$(builddir)/protoc" "--proto_path=." "./password_specifics$(suffix $<)" "--cpp_out=$(obj)/gen/protoc_out/chrome/browser/sync/protocol" "--python_out=$(builddir)/pyproto/sync_pb"
quiet_cmd_sync_proto_genproto_6 = RULE sync_proto_genproto_6 $@

$(builddir)/pyproto/sync_pb/preference_specifics_pb2.py: obj := $(abs_obj)

$(builddir)/pyproto/sync_pb/preference_specifics_pb2.py: builddir := $(abs_builddir)

$(builddir)/pyproto/sync_pb/preference_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync_pb/preference_specifics_pb2.py: chrome/browser/sync/protocol/preference_specifics.proto $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,sync_proto_genproto_7)
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/preference_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/preference_specifics.pb.cc: $(builddir)/pyproto/sync_pb/preference_specifics_pb2.py
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/preference_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/preference_specifics.pb.cc: ;

all_deps += $(builddir)/pyproto/sync_pb/preference_specifics_pb2.py $(obj)/gen/protoc_out/chrome/browser/sync/protocol/preference_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/preference_specifics.pb.cc
cmd_sync_proto_genproto_7 = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd chrome/browser/sync/protocol; mkdir -p $(obj)/gen/protoc_out/chrome/browser/sync/protocol $(builddir)/pyproto/sync_pb; "$(builddir)/protoc" "--proto_path=." "./preference_specifics$(suffix $<)" "--cpp_out=$(obj)/gen/protoc_out/chrome/browser/sync/protocol" "--python_out=$(builddir)/pyproto/sync_pb"
quiet_cmd_sync_proto_genproto_7 = RULE sync_proto_genproto_7 $@

$(builddir)/pyproto/sync_pb/theme_specifics_pb2.py: obj := $(abs_obj)

$(builddir)/pyproto/sync_pb/theme_specifics_pb2.py: builddir := $(abs_builddir)

$(builddir)/pyproto/sync_pb/theme_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync_pb/theme_specifics_pb2.py: chrome/browser/sync/protocol/theme_specifics.proto $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,sync_proto_genproto_8)
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/theme_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/theme_specifics.pb.cc: $(builddir)/pyproto/sync_pb/theme_specifics_pb2.py
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/theme_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/theme_specifics.pb.cc: ;

all_deps += $(builddir)/pyproto/sync_pb/theme_specifics_pb2.py $(obj)/gen/protoc_out/chrome/browser/sync/protocol/theme_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/theme_specifics.pb.cc
cmd_sync_proto_genproto_8 = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd chrome/browser/sync/protocol; mkdir -p $(obj)/gen/protoc_out/chrome/browser/sync/protocol $(builddir)/pyproto/sync_pb; "$(builddir)/protoc" "--proto_path=." "./theme_specifics$(suffix $<)" "--cpp_out=$(obj)/gen/protoc_out/chrome/browser/sync/protocol" "--python_out=$(builddir)/pyproto/sync_pb"
quiet_cmd_sync_proto_genproto_8 = RULE sync_proto_genproto_8 $@

$(builddir)/pyproto/sync_pb/typed_url_specifics_pb2.py: obj := $(abs_obj)

$(builddir)/pyproto/sync_pb/typed_url_specifics_pb2.py: builddir := $(abs_builddir)

$(builddir)/pyproto/sync_pb/typed_url_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync_pb/typed_url_specifics_pb2.py: chrome/browser/sync/protocol/typed_url_specifics.proto $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,sync_proto_genproto_9)
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/typed_url_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/typed_url_specifics.pb.cc: $(builddir)/pyproto/sync_pb/typed_url_specifics_pb2.py
$(obj)/gen/protoc_out/chrome/browser/sync/protocol/typed_url_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/typed_url_specifics.pb.cc: ;

all_deps += $(builddir)/pyproto/sync_pb/typed_url_specifics_pb2.py $(obj)/gen/protoc_out/chrome/browser/sync/protocol/typed_url_specifics.pb.h $(obj)/gen/protoc_out/chrome/browser/sync/protocol/typed_url_specifics.pb.cc
cmd_sync_proto_genproto_9 = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd chrome/browser/sync/protocol; mkdir -p $(obj)/gen/protoc_out/chrome/browser/sync/protocol $(builddir)/pyproto/sync_pb; "$(builddir)/protoc" "--proto_path=." "./typed_url_specifics$(suffix $<)" "--cpp_out=$(obj)/gen/protoc_out/chrome/browser/sync/protocol" "--python_out=$(builddir)/pyproto/sync_pb"
quiet_cmd_sync_proto_genproto_9 = RULE sync_proto_genproto_9 $@

rule_sync_proto_genproto_outputs := $(builddir)/pyproto/sync_pb/sync_pb2.py \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/sync.pb.h \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/sync.pb.cc \
	$(builddir)/pyproto/sync_pb/encryption_pb2.py \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/encryption.pb.h \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/encryption.pb.cc \
	$(builddir)/pyproto/sync_pb/autofill_specifics_pb2.py \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/autofill_specifics.pb.h \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/autofill_specifics.pb.cc \
	$(builddir)/pyproto/sync_pb/bookmark_specifics_pb2.py \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/bookmark_specifics.pb.h \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/bookmark_specifics.pb.cc \
	$(builddir)/pyproto/sync_pb/extension_specifics_pb2.py \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/extension_specifics.pb.h \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/extension_specifics.pb.cc \
	$(builddir)/pyproto/sync_pb/nigori_specifics_pb2.py \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/nigori_specifics.pb.h \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/nigori_specifics.pb.cc \
	$(builddir)/pyproto/sync_pb/password_specifics_pb2.py \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/password_specifics.pb.h \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/password_specifics.pb.cc \
	$(builddir)/pyproto/sync_pb/preference_specifics_pb2.py \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/preference_specifics.pb.h \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/preference_specifics.pb.cc \
	$(builddir)/pyproto/sync_pb/theme_specifics_pb2.py \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/theme_specifics.pb.h \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/theme_specifics.pb.cc \
	$(builddir)/pyproto/sync_pb/typed_url_specifics_pb2.py \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/typed_url_specifics.pb.h \
	$(obj)/gen/protoc_out/chrome/browser/sync/protocol/typed_url_specifics.pb.cc

### Finished generating for rule: sync_proto_genproto

### Finished generating for all rules

DEFS_Debug := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-D_DEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-O0 \
	-g

# Flags passed to only C (and not C++) files.
CFLAGS_C_Debug := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := 

DEFS_Release := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to both C and C++ files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C (and not C++) files.
CFLAGS_C_Release := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := 

OBJS := 

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | protoc

# Make sure our actions/rules run before any of us.
$(OBJS): | $(rule_sync_proto_genproto_outputs)


### Rules for final target.
# Build our special outputs first.
$(obj).target/chrome/browser/sync/protocol/sync_proto.stamp: | $(rule_sync_proto_genproto_outputs)

# Preserve order dependency of special output on deps.
$(rule_sync_proto_genproto_outputs): | protoc

$(obj).target/chrome/browser/sync/protocol/sync_proto.stamp: TOOLSET := $(TOOLSET)
$(obj).target/chrome/browser/sync/protocol/sync_proto.stamp: protoc FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/chrome/browser/sync/protocol/sync_proto.stamp
# Add target alias
.PHONY: sync_proto
sync_proto: $(obj).target/chrome/browser/sync/protocol/sync_proto.stamp

# Add target alias to "all" target.
.PHONY: all
all: sync_proto

