# This file is generated by gyp; do not edit.

export builddir_name ?= /usr/local/google/src/chromium-merge/src/chrome/browser/sync/protocol/out
.PHONY: all
all:
	$(MAKE) -C ../../../.. sync_proto sync_proto_cpp
