# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := allocator
DEFS_Debug := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-D_DEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Debug := -pthread \
	-fno-exceptions \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-pipe \
	-fno-strict-aliasing \
	-DNO_HEAP_CHECK \
	-O0 \
	-g

# Flags passed to only C (and not C++) files.
CFLAGS_C_Debug := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := -Ibase/allocator \
	-Ithird_party/tcmalloc/chromium/src/base \
	-Ithird_party/tcmalloc/chromium/src \
	-I.

DEFS_Release := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to both C and C++ files.
CFLAGS_Release := -pthread \
	-fno-exceptions \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-pipe \
	-fno-strict-aliasing \
	-DNO_HEAP_CHECK \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C (and not C++) files.
CFLAGS_C_Release := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := -Ibase/allocator \
	-Ithird_party/tcmalloc/chromium/src/base \
	-Ithird_party/tcmalloc/chromium/src \
	-I.

OBJS := $(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/base/linuxthreads.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/base/logging.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/base/low_level_alloc.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/base/spinlock.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/base/sysinfo.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/base/thread_lister.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/base/vdso_support.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/central_freelist.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/common.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/heap-profile-table.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/heap-profiler.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/internal_logging.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/malloc_extension.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/malloc_hook.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/maybe_threads.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/memory_region_map.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/page_heap.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/profile-handler.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/profiledata.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/profiler.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/raw_printer.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/sampler.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/span.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/stack_trace_table.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/stacktrace.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/static_vars.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/symbolize.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/system-alloc.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/tcmalloc.o \
	$(obj).target/$(TARGET)/third_party/tcmalloc/chromium/src/thread_cache.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := 

$(obj).target/base/allocator/liballocator.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/base/allocator/liballocator.a: LIBS := $(LIBS)
$(obj).target/base/allocator/liballocator.a: TOOLSET := $(TOOLSET)
$(obj).target/base/allocator/liballocator.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/base/allocator/liballocator.a
# Add target alias
.PHONY: allocator
allocator: $(obj).target/base/allocator/liballocator.a

# Add target alias to "all" target.
.PHONY: all
all: allocator

