# This file is generated by gyp; do not edit.

export builddir_name ?= /usr/local/google/src/chromium-merge/src/chrome/browser/sync/tools/out
.PHONY: all
all:
	$(MAKE) -C ../../../.. sync_listen_notifications
