# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := base
DEFS_Debug := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-D__STDC_FORMAT_MACROS' \
	'-DUSE_SYMBOLIZE' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-D_DEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-pthread \
	-D_REENTRANT \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/glib-2.0/include \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/directfb \
	-I/usr/include/libpng12 \
	-I../net/third_party/nss/ssl \
	-Inet/third_party/nss/ssl \
	-IWebKit/chromium/net/third_party/nss/ssl \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-Wno-write-strings \
	-O0 \
	-g

# Flags passed to only C (and not C++) files.
CFLAGS_C_Debug := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := -I.

DEFS_Release := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-D__STDC_FORMAT_MACROS' \
	'-DUSE_SYMBOLIZE' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to both C and C++ files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-pthread \
	-D_REENTRANT \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/glib-2.0/include \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/directfb \
	-I/usr/include/libpng12 \
	-I../net/third_party/nss/ssl \
	-Inet/third_party/nss/ssl \
	-IWebKit/chromium/net/third_party/nss/ssl \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-Wno-write-strings \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C (and not C++) files.
CFLAGS_C_Release := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := -I.

OBJS := $(obj).target/$(TARGET)/base/third_party/dmg_fp/dtoa.o \
	$(obj).target/$(TARGET)/base/third_party/dmg_fp/g_fmt.o \
	$(obj).target/$(TARGET)/base/third_party/icu/icu_utf.o \
	$(obj).target/$(TARGET)/base/third_party/nspr/prtime.o \
	$(obj).target/$(TARGET)/base/at_exit.o \
	$(obj).target/$(TARGET)/base/atomicops_internals_x86_gcc.o \
	$(obj).target/$(TARGET)/base/base_paths.o \
	$(obj).target/$(TARGET)/base/base_paths_posix.o \
	$(obj).target/$(TARGET)/base/base_switches.o \
	$(obj).target/$(TARGET)/base/bzip2_error_handler.o \
	$(obj).target/$(TARGET)/base/cancellation_flag.o \
	$(obj).target/$(TARGET)/base/command_line.o \
	$(obj).target/$(TARGET)/base/condition_variable_posix.o \
	$(obj).target/$(TARGET)/base/debug_util.o \
	$(obj).target/$(TARGET)/base/debug_util_posix.o \
	$(obj).target/$(TARGET)/base/env_var.o \
	$(obj).target/$(TARGET)/base/event_synthesis_gtk.o \
	$(obj).target/$(TARGET)/base/file_path.o \
	$(obj).target/$(TARGET)/base/file_util.o \
	$(obj).target/$(TARGET)/base/file_util_posix.o \
	$(obj).target/$(TARGET)/base/global_descriptors_posix.o \
	$(obj).target/$(TARGET)/base/gtk_util.o \
	$(obj).target/$(TARGET)/base/histogram.o \
	$(obj).target/$(TARGET)/base/lazy_instance.o \
	$(obj).target/$(TARGET)/base/lock.o \
	$(obj).target/$(TARGET)/base/lock_impl_posix.o \
	$(obj).target/$(TARGET)/base/logging.o \
	$(obj).target/$(TARGET)/base/memory_debug.o \
	$(obj).target/$(TARGET)/base/message_loop.o \
	$(obj).target/$(TARGET)/base/message_loop_proxy_impl.o \
	$(obj).target/$(TARGET)/base/message_pump_default.o \
	$(obj).target/$(TARGET)/base/mime_util_xdg.o \
	$(obj).target/$(TARGET)/base/native_library_linux.o \
	$(obj).target/$(TARGET)/base/non_thread_safe.o \
	$(obj).target/$(TARGET)/base/path_service.o \
	$(obj).target/$(TARGET)/base/pickle.o \
	$(obj).target/$(TARGET)/base/platform_file_posix.o \
	$(obj).target/$(TARGET)/base/platform_thread_posix.o \
	$(obj).target/$(TARGET)/base/process_linux.o \
	$(obj).target/$(TARGET)/base/process_posix.o \
	$(obj).target/$(TARGET)/base/process_util.o \
	$(obj).target/$(TARGET)/base/process_util_linux.o \
	$(obj).target/$(TARGET)/base/process_util_posix.o \
	$(obj).target/$(TARGET)/base/profiler.o \
	$(obj).target/$(TARGET)/base/rand_util.o \
	$(obj).target/$(TARGET)/base/rand_util_posix.o \
	$(obj).target/$(TARGET)/base/ref_counted.o \
	$(obj).target/$(TARGET)/base/safe_strerror_posix.o \
	$(obj).target/$(TARGET)/base/scoped_temp_dir.o \
	$(obj).target/$(TARGET)/base/sha1_portable.o \
	$(obj).target/$(TARGET)/base/shared_memory_posix.o \
	$(obj).target/$(TARGET)/base/simple_thread.o \
	$(obj).target/$(TARGET)/base/stats_table.o \
	$(obj).target/$(TARGET)/base/string_piece.o \
	$(obj).target/$(TARGET)/base/string_split.o \
	$(obj).target/$(TARGET)/base/string_util.o \
	$(obj).target/$(TARGET)/base/sys_info_linux.o \
	$(obj).target/$(TARGET)/base/sys_info_posix.o \
	$(obj).target/$(TARGET)/base/sys_string_conversions_linux.o \
	$(obj).target/$(TARGET)/base/task.o \
	$(obj).target/$(TARGET)/base/thread.o \
	$(obj).target/$(TARGET)/base/thread_collision_warner.o \
	$(obj).target/$(TARGET)/base/thread_local_posix.o \
	$(obj).target/$(TARGET)/base/thread_local_storage_posix.o \
	$(obj).target/$(TARGET)/base/time.o \
	$(obj).target/$(TARGET)/base/timer.o \
	$(obj).target/$(TARGET)/base/trace_event.o \
	$(obj).target/$(TARGET)/base/tracked.o \
	$(obj).target/$(TARGET)/base/tracked_objects.o \
	$(obj).target/$(TARGET)/base/unix_domain_socket_posix.o \
	$(obj).target/$(TARGET)/base/utf_offset_string_conversions.o \
	$(obj).target/$(TARGET)/base/utf_string_conversion_utils.o \
	$(obj).target/$(TARGET)/base/utf_string_conversions.o \
	$(obj).target/$(TARGET)/base/values.o \
	$(obj).target/$(TARGET)/base/waitable_event_posix.o \
	$(obj).target/$(TARGET)/base/waitable_event_watcher_posix.o \
	$(obj).target/$(TARGET)/base/watchdog.o \
	$(obj).target/$(TARGET)/base/weak_ptr.o \
	$(obj).target/$(TARGET)/base/worker_pool_linux.o \
	$(obj).target/$(TARGET)/base/xdg_util.o \
	$(obj).target/$(TARGET)/base/crypto/encryptor_nss.o \
	$(obj).target/$(TARGET)/base/crypto/rsa_private_key.o \
	$(obj).target/$(TARGET)/base/crypto/rsa_private_key_nss.o \
	$(obj).target/$(TARGET)/base/crypto/signature_creator_nss.o \
	$(obj).target/$(TARGET)/base/crypto/signature_verifier_nss.o \
	$(obj).target/$(TARGET)/base/crypto/symmetric_key_nss.o \
	$(obj).target/$(TARGET)/base/third_party/nss/sha512.o \
	$(obj).target/$(TARGET)/base/third_party/xdg_user_dirs/xdg_user_dir_lookup.o \
	$(obj).target/$(TARGET)/base/base64.o \
	$(obj).target/$(TARGET)/base/data_pack.o \
	$(obj).target/$(TARGET)/base/event_recorder_stubs.o \
	$(obj).target/$(TARGET)/base/field_trial.o \
	$(obj).target/$(TARGET)/base/file_descriptor_shuffle.o \
	$(obj).target/$(TARGET)/base/hmac_nss.o \
	$(obj).target/$(TARGET)/base/json/json_reader.o \
	$(obj).target/$(TARGET)/base/json/json_writer.o \
	$(obj).target/$(TARGET)/base/json/string_escape.o \
	$(obj).target/$(TARGET)/base/keyboard_code_conversion_gtk.o \
	$(obj).target/$(TARGET)/base/linux_util.o \
	$(obj).target/$(TARGET)/base/md5.o \
	$(obj).target/$(TARGET)/base/message_pump_glib.o \
	$(obj).target/$(TARGET)/base/message_pump_libevent.o \
	$(obj).target/$(TARGET)/base/nss_util.o \
	$(obj).target/$(TARGET)/base/setproctitle_linux.o \
	$(obj).target/$(TARGET)/base/sha2.o \
	$(obj).target/$(TARGET)/base/string16.o \
	$(obj).target/$(TARGET)/base/sync_socket_posix.o \
	$(obj).target/$(TARGET)/base/time_posix.o \
	$(obj).target/$(TARGET)/base/version.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/build/util/lastchange.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack \
	-rdynamic

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,--gc-sections

LIBS := 

$(obj).target/base/libbase.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/base/libbase.a: LIBS := $(LIBS)
$(obj).target/base/libbase.a: TOOLSET := $(TOOLSET)
$(obj).target/base/libbase.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/base/libbase.a
# Add target alias
.PHONY: base
base: $(obj).target/base/libbase.a

# Add target alias to "all" target.
.PHONY: all
all: base

