# This file is generated by gyp; do not edit.

export builddir_name ?= /usr/local/google/src/chromium-merge/src/base/out
.PHONY: all
all:
	$(MAKE) -C .. symbolize xdg_mime base test_support_perf test_support_base base_i18n base_unittests
