# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := base_unittests
DEFS_Debug := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-D_DEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fno-strict-aliasing \
	-pthread \
	-D_REENTRANT \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/glib-2.0/include \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/directfb \
	-I/usr/include/libpng12 \
	-I../net/third_party/nss/ssl \
	-Inet/third_party/nss/ssl \
	-IWebKit/chromium/net/third_party/nss/ssl \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-O0 \
	-g

# Flags passed to only C (and not C++) files.
CFLAGS_C_Debug := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := -Ithird_party/icu/public/common \
	-I. \
	-Itesting/gmock/include \
	-Itesting/gtest/include

DEFS_Release := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_GPU=1' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to both C and C++ files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fno-strict-aliasing \
	-pthread \
	-D_REENTRANT \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/glib-2.0/include \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/directfb \
	-I/usr/include/libpng12 \
	-I../net/third_party/nss/ssl \
	-Inet/third_party/nss/ssl \
	-IWebKit/chromium/net/third_party/nss/ssl \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C (and not C++) files.
CFLAGS_C_Release := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := -Ithird_party/icu/public/common \
	-I. \
	-Itesting/gmock/include \
	-Itesting/gtest/include

OBJS := $(obj).target/$(TARGET)/base/test/run_all_unittests.o \
	$(obj).target/$(TARGET)/base/at_exit_unittest.o \
	$(obj).target/$(TARGET)/base/atomicops_unittest.o \
	$(obj).target/$(TARGET)/base/base64_unittest.o \
	$(obj).target/$(TARGET)/base/bits_unittest.o \
	$(obj).target/$(TARGET)/base/callback_unittest.o \
	$(obj).target/$(TARGET)/base/cancellation_flag_unittest.o \
	$(obj).target/$(TARGET)/base/command_line_unittest.o \
	$(obj).target/$(TARGET)/base/condition_variable_unittest.o \
	$(obj).target/$(TARGET)/base/crypto/encryptor_unittest.o \
	$(obj).target/$(TARGET)/base/crypto/rsa_private_key_unittest.o \
	$(obj).target/$(TARGET)/base/crypto/rsa_private_key_nss_unittest.o \
	$(obj).target/$(TARGET)/base/crypto/signature_creator_unittest.o \
	$(obj).target/$(TARGET)/base/crypto/signature_verifier_unittest.o \
	$(obj).target/$(TARGET)/base/crypto/symmetric_key_unittest.o \
	$(obj).target/$(TARGET)/base/data_pack_unittest.o \
	$(obj).target/$(TARGET)/base/debug_util_unittest.o \
	$(obj).target/$(TARGET)/base/dir_reader_posix_unittest.o \
	$(obj).target/$(TARGET)/base/environment_unittest.o \
	$(obj).target/$(TARGET)/base/field_trial_unittest.o \
	$(obj).target/$(TARGET)/base/file_descriptor_shuffle_unittest.o \
	$(obj).target/$(TARGET)/base/file_path_unittest.o \
	$(obj).target/$(TARGET)/base/file_util_unittest.o \
	$(obj).target/$(TARGET)/base/gmock_unittest.o \
	$(obj).target/$(TARGET)/base/histogram_unittest.o \
	$(obj).target/$(TARGET)/base/hmac_unittest.o \
	$(obj).target/$(TARGET)/base/id_map_unittest.o \
	$(obj).target/$(TARGET)/base/i18n/char_iterator_unittest.o \
	$(obj).target/$(TARGET)/base/i18n/file_util_icu_unittest.o \
	$(obj).target/$(TARGET)/base/i18n/icu_string_conversions_unittest.o \
	$(obj).target/$(TARGET)/base/i18n/rtl_unittest.o \
	$(obj).target/$(TARGET)/base/i18n/word_iterator_unittest.o \
	$(obj).target/$(TARGET)/base/json/json_reader_unittest.o \
	$(obj).target/$(TARGET)/base/json/json_writer_unittest.o \
	$(obj).target/$(TARGET)/base/json/string_escape_unittest.o \
	$(obj).target/$(TARGET)/base/lazy_instance_unittest.o \
	$(obj).target/$(TARGET)/base/leak_tracker_unittest.o \
	$(obj).target/$(TARGET)/base/linked_list_unittest.o \
	$(obj).target/$(TARGET)/base/linked_ptr_unittest.o \
	$(obj).target/$(TARGET)/base/lock_unittest.o \
	$(obj).target/$(TARGET)/base/message_loop_proxy_impl_unittest.o \
	$(obj).target/$(TARGET)/base/message_loop_unittest.o \
	$(obj).target/$(TARGET)/base/message_pump_glib_unittest.o \
	$(obj).target/$(TARGET)/base/non_thread_safe_unittest.o \
	$(obj).target/$(TARGET)/base/observer_list_unittest.o \
	$(obj).target/$(TARGET)/base/path_service_unittest.o \
	$(obj).target/$(TARGET)/base/pickle_unittest.o \
	$(obj).target/$(TARGET)/base/platform_file_unittest.o \
	$(obj).target/$(TARGET)/base/platform_thread_unittest.o \
	$(obj).target/$(TARGET)/base/pr_time_unittest.o \
	$(obj).target/$(TARGET)/base/process_util_unittest.o \
	$(obj).target/$(TARGET)/base/rand_util_unittest.o \
	$(obj).target/$(TARGET)/base/ref_counted_unittest.o \
	$(obj).target/$(TARGET)/base/scoped_native_library_unittest.o \
	$(obj).target/$(TARGET)/base/scoped_ptr_unittest.o \
	$(obj).target/$(TARGET)/base/scoped_temp_dir_unittest.o \
	$(obj).target/$(TARGET)/base/sha1_unittest.o \
	$(obj).target/$(TARGET)/base/sha2_unittest.o \
	$(obj).target/$(TARGET)/base/shared_memory_unittest.o \
	$(obj).target/$(TARGET)/base/simple_thread_unittest.o \
	$(obj).target/$(TARGET)/base/singleton_unittest.o \
	$(obj).target/$(TARGET)/base/stack_container_unittest.o \
	$(obj).target/$(TARGET)/base/stats_table_unittest.o \
	$(obj).target/$(TARGET)/base/string_number_conversions_unittest.o \
	$(obj).target/$(TARGET)/base/string_piece_unittest.o \
	$(obj).target/$(TARGET)/base/string_split_unittest.o \
	$(obj).target/$(TARGET)/base/string_tokenizer_unittest.o \
	$(obj).target/$(TARGET)/base/string_util_unittest.o \
	$(obj).target/$(TARGET)/base/stringprintf_unittest.o \
	$(obj).target/$(TARGET)/base/sys_info_unittest.o \
	$(obj).target/$(TARGET)/base/sys_string_conversions_unittest.o \
	$(obj).target/$(TARGET)/base/task_queue_unittest.o \
	$(obj).target/$(TARGET)/base/thread_checker_unittest.o \
	$(obj).target/$(TARGET)/base/thread_collision_warner_unittest.o \
	$(obj).target/$(TARGET)/base/thread_local_storage_unittest.o \
	$(obj).target/$(TARGET)/base/thread_local_unittest.o \
	$(obj).target/$(TARGET)/base/thread_unittest.o \
	$(obj).target/$(TARGET)/base/time_unittest.o \
	$(obj).target/$(TARGET)/base/timer_unittest.o \
	$(obj).target/$(TARGET)/base/tools_sanity_unittest.o \
	$(obj).target/$(TARGET)/base/tracked_objects_unittest.o \
	$(obj).target/$(TARGET)/base/tuple_unittest.o \
	$(obj).target/$(TARGET)/base/utf_offset_string_conversions_unittest.o \
	$(obj).target/$(TARGET)/base/utf_string_conversions_unittest.o \
	$(obj).target/$(TARGET)/base/values_unittest.o \
	$(obj).target/$(TARGET)/base/version_unittest.o \
	$(obj).target/$(TARGET)/base/vlog_unittest.o \
	$(obj).target/$(TARGET)/base/waitable_event_unittest.o \
	$(obj).target/$(TARGET)/base/waitable_event_watcher_unittest.o \
	$(obj).target/$(TARGET)/base/watchdog_unittest.o \
	$(obj).target/$(TARGET)/base/weak_ptr_unittest.o \
	$(obj).target/$(TARGET)/base/worker_pool_unittest.o \
	$(obj).target/$(TARGET)/base/xdg_util_unittest.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/base/libbase.a $(obj).target/base/libbase_i18n.a $(obj).target/base/libtest_support_base.a $(obj).target/testing/libgmock.a $(obj).target/testing/libgtest.a xdisplaycheck $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/base/third_party/dynamic_annotations/libdynamic_annotations.a $(obj).target/base/libsymbolize.a $(obj).target/net/third_party/nss/libssl.a $(obj).target/third_party/zlib/libzlib.a $(obj).target/base/libxdg_mime.a $(obj).target/base/allocator/liballocator.a $(obj).target/third_party/libevent/libevent.a $(obj).target/third_party/icu/libicui18n.a $(obj).target/third_party/icu/libicuuc.a $(obj).target/third_party/icu/libicudata.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack \
	-Wl,-uIsHeapProfilerRunning,-uProfilerStart \
	-Wl,-u_Z21InitialMallocHook_NewPKvj,-u_Z22InitialMallocHook_MMapPKvS0_jiiix,-u_Z22InitialMallocHook_SbrkPKvi \
	-Wl,-u_Z21InitialMallocHook_NewPKvm,-u_Z22InitialMallocHook_MMapPKvS0_miiil,-u_Z22InitialMallocHook_SbrkPKvl

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,-uIsHeapProfilerRunning,-uProfilerStart \
	-Wl,-u_Z21InitialMallocHook_NewPKvj,-u_Z22InitialMallocHook_MMapPKvS0_jiiix,-u_Z22InitialMallocHook_SbrkPKvi \
	-Wl,-u_Z21InitialMallocHook_NewPKvm,-u_Z22InitialMallocHook_MMapPKvS0_miiil,-u_Z22InitialMallocHook_SbrkPKvl \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := -lrt \
	-ldl \
	-lgtk-x11-2.0 \
	-lgdk-x11-2.0 \
	-latk-1.0 \
	-lgio-2.0 \
	-lpangoft2-1.0 \
	-lgdk_pixbuf-2.0 \
	-lm \
	-lpangocairo-1.0 \
	-lcairo \
	-lpango-1.0 \
	-lfreetype \
	-lfontconfig \
	-lgobject-2.0 \
	-lgmodule-2.0 \
	-lgthread-2.0 \
	-lglib-2.0 \
	-lnss3 \
	-lnssutil3 \
	-lsmime3 \
	-lplds4 \
	-lplc4 \
	-lnspr4 \
	-lpthread \
	-lz

$(builddir)/base_unittests: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/base_unittests: LIBS := $(LIBS)
$(builddir)/base_unittests: TOOLSET := $(TOOLSET)
$(builddir)/base_unittests: $(OBJS) $(obj).target/base/libbase.a $(obj).target/base/libbase_i18n.a $(obj).target/base/libtest_support_base.a $(obj).target/testing/libgmock.a $(obj).target/testing/libgtest.a $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/base/third_party/dynamic_annotations/libdynamic_annotations.a $(obj).target/base/libsymbolize.a $(obj).target/net/third_party/nss/libssl.a $(obj).target/third_party/zlib/libzlib.a $(obj).target/base/libxdg_mime.a $(obj).target/base/allocator/liballocator.a $(obj).target/third_party/libevent/libevent.a $(obj).target/third_party/icu/libicui18n.a $(obj).target/third_party/icu/libicuuc.a $(obj).target/third_party/icu/libicudata.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/base_unittests
# Add target alias
.PHONY: base_unittests
base_unittests: $(builddir)/base_unittests

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/base_unittests

