# This file is generated by gyp; do not edit.

export builddir_name ?= /usr/local/google/src/chromium-merge/src/base/out
.PHONY: all
all:
	$(MAKE) -C .. xdg_mime symbolize base base_i18n test_support_perf test_support_base base_unittests
