# This file is generated by gyp; do not edit.

export builddir_name ?= /usr/local/google/src/chromium-merge/src/net/out
.PHONY: all
all:
	$(MAKE) -C .. ssl_false_start_blacklist_process net_resources tld_cleanup net_base hresolv dnssec_chain_verify net net_test_support http_listen_socket fetch_server fetch_client net_unittests net_perftests run_testserver stress_cache crash_cache
